### PR TITLE
[WIP] feat: UI to allow users to manage different AI models

### PR DESCRIPTION
**Pull request by Jacksonmills**
The restructuring aims to offer a more intuitive layout, reducing clutter and focusing more on user engagement with conversations. The addition of the SettingsDialog provides a designated area for personalization without overwhelming the main interface.

https://github.com/adamcohenhillel/ADeus/issues/69

### CODE REVIEW

**Comment by Jacksonmills** [comment]
Lots of work for the actual handling of these ui parts as these are all mostly hardcoded until we plan out the feature of how exactly we will set up models in the settings menu then populate the model menu with the active models in your settings

**Comment by adamcohenhillel** [comment]
seems like there is a conflict in Chat.tsx

**Comment by Jacksonmills** [comment]
> seems like there is a conflict in Chat.tsx

I'll update you as I work more on this. My thinking is to set up some React context for active/setup models, then use Capacitor storage like we did with Supabase auth. I've been worrying purely about the frontend because I don't have a full understanding of what's needed yet.

Maybe we can align more on how the models work and such, so I can get a better picture of how this needs to work.

**Comment by Jacksonmills** [comment]
@adamcohenhillel https://github.com/adamcohenhillel/ADeus/issues/69 this issue is where I think it would be good to plan out this feature, whenever we want to prioritize it.

**Comment by makeiteasierapps** [comment]
I think having a drop down to select your model would be nice, sounds like you are implementing that? Right now the backend code checks if certain env variables are truthy and if so it uses that particular chatClient. Ideally a user could have multiple models they are trying out. It would be more robust to send the chatClient as a prop then on the backend we can just deconstruct the chatClient and use it. That would clean the code up and make it more flexible.

**Comment by Jacksonmills** [comment]
> I think having a drop down to select your model would be nice, sounds like you are implementing that? Right now the backend code checks if certain env variables are truthy and if so it uses that particular chatClient. Ideally a user could have multiple models they are trying out. It would be more robust to send the chatClient as a prop then on the backend we can just deconstruct the chatClient and use it. That would clean the code up and make it more flexible.

Totally, I was also picturing a settings modal to set your keys for each model, but currently we do that within the setup process right? So just need a way to either just detect them and populate the dropdown or add the settings to the frontend to add models to supabase/capacitor storage.

Maybe a good first step is just the dropdown?

**Comment by Jacksonmills** [comment]
I see in the supabase function we are just checking if the key exists and it will just override which model so we will need to rework how that works either way

**Comment by Jacksonmills** [comment]
image
image

So I added react context that can control the current selected model, however I may need some input on the best way we can handle model api keys in the frontend and pass which one to use/the key itself into the supabase function(?), LMK what you think frontend wise asw!

**Comment by Jacksonmills** [comment]
Probably worth thinking about adding which model is used to each convo as well?

**Pull request closed without merging**
