### PR TITLE
Supabase hook cleanup/Cleaner Index

### PR DESCRIPTION
**Pull request by Jacksonmills**

### CODE REVIEW

**Comment by adamcohenhillel** [comment]
Looks neat! but It seems to be stuck on the loading component :

image


(check out the Vercel preview)

**Comment by Jacksonmills** [comment]
> Looks neat! but It seems to be stuck on the loading component :
> image
> 
> (check out the Vercel preview)

Ah yeah I see as a new user/incognito it defaults to loading, let me figure out that edge case.

**Comment by adamcohenhillel** [comment]
Need to wait for this? https://github.com/adamcohenhillel/ADeus/issues/19

**Comment by Jacksonmills** [comment]
> Need to wait for this? #19

We could, but this is done in that I only really meant to fix the 'any' in the supabase hook in the ticket

**Pull request merged**
